# SPDX-FileCopyrightText: 2022 Iconica
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: flutter_registration
description: A Flutter Registration package
version: 1.2.0
repository: https://github.com/Iconica-Development/flutter_registration

publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_input_library:
    git:
      url: https://github.com/Iconica-Development/flutter_input_library
      ref: 3.0.0

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
